name: page deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    steps:
      - name: Deploy page
        uses: appleboy/scp-action@master
        env:
          HOST: 57.128.84.35
          USERNAME: root
          PASSWORD: tamimpomme
      - name: Test
        run: wall test

