name: page deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: debian-latest

    steps:
      - uses: actions/checkout@main
      - name: deploy page
      - uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: wall test
