name: Deploy Nextcloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy Nextcloud
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /path/to/nextcloud
          ./deploy-nextcloud.sh
